### ISSUE TITLE
Option to have Column one as header too?

### ISSUE THREAD

**Issue by steve21124** [allaboutapps/A3GridTableView#3]
currently, only row 1 as header. it is possible to have both row 1 and column as header. just like matrix which are not moving.

**Comment by BotiKis** [comment]
Hi.
No that's not possible and there are no plans to implement this feature since with iOS 6 there is a great thing called UICollectionView which can perform this task quite easy using a custom UICollectionViewFlowLayout.  
You can see how this works at the [Collection View Programming Guide for iOS](https://developer.apple.com/library/ios/documentation/WindowsViews/Conceptual/CollectionViewPGforIOS/UsingtheFlowLayout/UsingtheFlowLayout.html)
